language: python
python:
- '2.7'
- '3.5'
- '3.6'
script: python setup.py test
deploy:
  provider: pypi
  user: acordiner
  password:
    secure: SvZjhypiog1bvpD9HpsPYQhyjoaLkQwuBCrRCE3JTLxczW30NoNh+DmA2gBGvleV+XL0kKsDnJM5/1anCrx5H/ODqzCYeomuj9bMJTFhofGbkBCxWpwBxMcSwVvUOKB8VwrpxZMGSODmx5ivz+J4Csy9dqphhVe6PyI5lcziaCHtbPSWcH7iEWjVa9sJZldCRUWkrjRtEGLFh2jPUL81x+AVix0vJxp/cTQRJxVKFfab6ZoZ/iKi43HoH9pq/WmyEcXYS4CgM3vD8RQvl+sUcQ4brEQmSI7mLMrSvP+GA/akb19yXz7YN9QyCbDeDok0ArkYuQLk2D1SqS3rWVFtrp80Uihg8V5e48yvrzG+XF2ZBQ6Y43wyBHNgS2NikaIJugA9JektB2jLPr009+cT1LUX+/srWtYd//NQ2Mu8K6uU6L4SVXK+fLA/iXIBq51nS7fe0ZSJSHvZYxi0fi8bHtNdeO9ejKiFzmjMM187PDdhUzM2CoI/rGBrDSUPHL0GAILvICDjpU6iwBc1F07chHXSik2Co4u4FYDhykGQrLpcs71AOKbKjilRJWiUT520LjebNNXksA4D5gnEbiNNxpgME+Xa6I6iuLX7HH+ThYmWLWZSJA1MuTkUpyqoEYNETkYXrtjZ6PDusdM4dsSAKYU3aLmb0Nmf5AnSf7jnTmg=
